version: '2'
services:
  wheelsshareapp-app:
    image: wheelsshareapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wheelsshareapp-postgresql:5432/WheelsShareApp
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  wheelsshareapp-postgresql:
    extends:
      file: postgresql.yml
      service: wheelsshareapp-postgresql
